DROP TABLE IF EXISTS POST;

CREATE TABLE POST (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  author_id INT NOT NULL,
  message VARCHAR(250) NOT NULL,
  origin INT NOT NULL,
  created_at DATETIME NOT NULL
);

DROP TABLE IF EXISTS USER;

CREATE TABLE USER (
  id INT AUTO_INCREMENT PRIMARY KEY,
  login VARCHAR(250) NOT NULL
);

DROP TABLE IF EXISTS FOLLOW;

CREATE TABLE FOLLOW (
  id INT AUTO_INCREMENT PRIMARY KEY,
  who_am_i INT NOT NULL,
  follow_id INT NOT NULL
);